hello_django3/urls.py
from django.contrib import admin
from django.urls import path, include
from pages.views import HomePageView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
]

pages/urls.py
from django.urls import path

from .views import HomePageView
from .views import AboutPageView

app_name = 'pages'
urlpatterns = [
    path('', HomePageView.as_view(), name='homepage'),
    path('about/', AboutPageView.as_view(), name='about'),
]

pages/models.py
from django.db import models

# Create your models here.

pages/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
# Create your views here.

class HomePageView(TemplateView):
    template_name = 'pages/home.html'

class AboutPageView(TemplateView):
    template_name = 'pages/about_us.html'

templates/_base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{% block title %}{% endblock %} | Hello, Django!</title>
</head>
<body>
<header>
<a href="{% url 'pages:homepage' %}">Home</a> |
<a href="{% url 'pages:about' %}">About</a>
</header>
<h1>{% block header %}Hello, Django!{% endblock %}</h1>
<main>
{% block main %}{% endblock %}
</main>
</body>
</html>

templates/pages/about_us.html
{% extends "_base.html" %}

{% block title %}About Us{% endblock %}
{% block header %}About Us{% endblock %}
{% block main %}
<p>Very interesting information about us!</p>
{% endblock %}

templates/pages/home.html
{% extends "_base.html" %}

{% block title %}Home{% endblock %}
{% block main %}
<p>Thank you for visiting our site!</p>
{% endblock %}